use crate::{Localizer, MessageId, FluentArgs};
use serde::Serialize;
use std::sync::Arc;

use crate::CommonCopy;

#[derive(Clone, Serialize)]
pub struct ProofCopy {
    pub common: CommonCopy,
    pub unavailable: Arc<str>,
    pub preparing: Arc<str>,
    pub preparing_sdr: Arc<str>,
    pub sdr_unavailable: Arc<str>,
    pub profile: Arc<str>,
    pub simulation: Arc<str>,
    pub intent: Arc<str>,
    pub black_point_compensation: Arc<str>,
    pub gamut_warning: Arc<str>,
    pub relative: Arc<str>,
    pub perceptual: Arc<str>,
    pub saturation: Arc<str>,
    pub absolute: Arc<str>,
    pub colors: Arc<str>,
    pub black_ink: Arc<str>,
    pub paper_ink: Arc<str>,
    pub balance: Arc<str>,
    pub contrast: Arc<str>,
    pub brightness: Arc<str>,
    pub highlight_color: Arc<str>,
    pub mode_off: Arc<str>,
    pub mode_print: Arc<str>,
    pub preparing_print: Arc<str>,
    pub contrast_scale: Arc<str>,
    pub tone_help: Arc<str>,
    pub reset_sdr: Arc<str>,
    pub normal: Arc<str>,
    pub preview_complete: Arc<str>,
    pub preparing_complete: Arc<str>,
    pub print_profile: Arc<str>,
    pub white: Arc<str>,
    pub color: Arc<str>,
    pub title: Arc<str>,
    pub mode: Arc<str>,
    pub balance_contrast: Arc<str>,
    pub profile_choice: Arc<str>,
    pub key_help: Arc<str>,
}
impl ProofCopy {
    pub fn new(localizer: &Localizer) -> Self {
        Self { common: CommonCopy::new(localizer),
            title: localizer.text(MessageId::COLOR_FEATURES_PROOF_TITLE),
            mode: localizer.text(MessageId::COLOR_FEATURES_PROOF_MODE),
            balance_contrast: localizer.text(MessageId::COLOR_FEATURES_PROOF_BALANCE_CONTRAST),
            profile_choice: localizer.text(MessageId::COLOR_FEATURES_PROOF_PROFILE_CHOICE),
            key_help: localizer.text(MessageId::COLOR_FEATURES_PROOF_KEY_HELP),

            unavailable: localizer.text(MessageId::COLOR_FEATURES_PROOF_UNAVAILABLE),
            preparing: localizer.text(MessageId::COLOR_FEATURES_PROOF_PREPARING),
            preparing_sdr: localizer.text(MessageId::COLOR_FEATURES_PROOF_PREPARING_SDR),
            sdr_unavailable: localizer.text(MessageId::COLOR_FEATURES_PROOF_SDR_UNAVAILABLE),
            profile: localizer.text(MessageId::COLOR_FEATURES_PROOF_PROFILE),
            simulation: localizer.text(MessageId::COLOR_FEATURES_PROOF_SIMULATION),
            intent: localizer.text(MessageId::COLOR_FEATURES_PROOF_INTENT),
            black_point_compensation: localizer.text(MessageId::COLOR_FEATURES_PROOF_BLACK_POINT_COMPENSATION),
            gamut_warning: localizer.text(MessageId::COLOR_FEATURES_PROOF_GAMUT_WARNING),
            relative: localizer.text(MessageId::COLOR_FEATURES_PROOF_RELATIVE),
            perceptual: localizer.text(MessageId::COLOR_FEATURES_PROOF_PERCEPTUAL),
            saturation: localizer.text(MessageId::COLOR_FEATURES_PROOF_SATURATION),
            absolute: localizer.text(MessageId::COLOR_FEATURES_PROOF_ABSOLUTE),
            colors: localizer.text(MessageId::COLOR_FEATURES_PROOF_COLORS),
            black_ink: localizer.text(MessageId::COLOR_FEATURES_PROOF_BLACK_INK),
            paper_ink: localizer.text(MessageId::COLOR_FEATURES_PROOF_PAPER_INK),
            balance: localizer.text(MessageId::COLOR_FEATURES_PROOF_BALANCE),
            contrast: localizer.text(MessageId::COLOR_FEATURES_PROOF_CONTRAST),
            brightness: localizer.text(MessageId::COLOR_FEATURES_PROOF_BRIGHTNESS),
            highlight_color: localizer.text(MessageId::COLOR_FEATURES_PROOF_HIGHLIGHT_COLOR),
            mode_off: localizer.text(MessageId::COLOR_FEATURES_PROOF_MODE_OFF),
            mode_print: localizer.text(MessageId::COLOR_FEATURES_PROOF_MODE_PRINT),
            preparing_print: localizer.text(MessageId::COLOR_FEATURES_PROOF_PREPARING_PRINT),
            contrast_scale: localizer.text(MessageId::COLOR_FEATURES_PROOF_CONTRAST_SCALE),
            tone_help: localizer.text(MessageId::COLOR_FEATURES_PROOF_TONE_HELP),
            reset_sdr: localizer.text(MessageId::COLOR_FEATURES_PROOF_RESET_SDR),
            normal: localizer.text(MessageId::COLOR_FEATURES_PROOF_NORMAL),
            preview_complete: localizer.text(MessageId::COLOR_FEATURES_PROOF_PREVIEW_COMPLETE),
            preparing_complete: localizer.text(MessageId::COLOR_FEATURES_PROOF_PREPARING_COMPLETE),
            print_profile: localizer.text(MessageId::COLOR_FEATURES_PROOF_PRINT_PROFILE),
            white: localizer.text(MessageId::COLOR_FEATURES_PROOF_WHITE),
            color: localizer.text(MessageId::COLOR_FEATURES_PROOF_COLOR),
        }
    }
}

#[derive(Clone, Serialize)]
pub struct ProfileCopy {
    pub read_bytes: usize,
    pub read_limit: Arc<str>,
    pub common: CommonCopy,
    pub reading: Arc<str>,
    pub choose: Arc<str>,
    pub choose_short: Arc<str>,
    pub choose_add: Arc<str>,
    pub filter: Arc<str>,
    pub add: Arc<str>,
    pub add_profile: Arc<str>,
    pub add_profile_dialog: Arc<str>,
    pub manage: Arc<str>,
    pub manage_title: Arc<str>,
    pub library_title: Arc<str>,
    pub library_help: Arc<str>,
    pub menu_help: Arc<str>,
    pub empty: Arc<str>,
    pub search: Arc<str>,
    pub loading: Arc<str>,
    pub document: Arc<str>,
    pub current: Arc<str>,
    pub saved: Arc<str>,
    pub saved_dialog: Arc<str>,
    pub standard: Arc<str>,
    pub import: Arc<str>,
    pub use_profile: Arc<str>,
    pub show: Arc<str>,
    pub hide: Arc<str>,
    pub shown: Arc<str>,
    pub remove: Arc<str>,
    pub embedded: Arc<str>,
    pub interpret_title: Arc<str>,
    pub interpret_help: Arc<str>,
    pub interpret_as: Arc<str>,
}
impl ProfileCopy {
    pub fn new(localizer: &Localizer) -> Self {
        Self { read_bytes: crate::profile_library::PROFILE_READ_LIMIT, read_limit: localizer.text(MessageId::COLOR_PROFILE_READ_LIMIT), common: CommonCopy::new(localizer),
            reading: localizer.text(MessageId::COLOR_FEATURES_PROFILE_READING),
            choose: localizer.text(MessageId::COLOR_FEATURES_PROFILE_CHOOSE),
            choose_short: localizer.text(MessageId::COLOR_FEATURES_PROFILE_CHOOSE_SHORT),
            choose_add: localizer.text(MessageId::COLOR_FEATURES_PROFILE_CHOOSE_ADD),
            filter: localizer.text(MessageId::COLOR_FEATURES_PROFILE_FILTER),
            add: localizer.text(MessageId::COLOR_FEATURES_PROFILE_ADD),
            add_profile: localizer.text(MessageId::COLOR_FEATURES_PROFILE_ADD_PROFILE),
            add_profile_dialog: localizer.text(MessageId::COLOR_FEATURES_PROFILE_ADD_PROFILE_DIALOG),
            manage: localizer.text(MessageId::COLOR_FEATURES_PROFILE_MANAGE),
            manage_title: localizer.text(MessageId::COLOR_FEATURES_PROFILE_MANAGE_TITLE),
            library_title: localizer.text(MessageId::COLOR_FEATURES_PROFILE_LIBRARY_TITLE),
            library_help: localizer.text(MessageId::COLOR_FEATURES_PROFILE_LIBRARY_HELP),
            menu_help: localizer.text(MessageId::COLOR_FEATURES_PROFILE_MENU_HELP),
            empty: localizer.text(MessageId::COLOR_FEATURES_PROFILE_EMPTY),
            search: localizer.text(MessageId::COLOR_FEATURES_PROFILE_SEARCH),
            loading: localizer.text(MessageId::COLOR_FEATURES_PROFILE_LOADING),
            document: localizer.text(MessageId::COLOR_FEATURES_PROFILE_DOCUMENT),
            current: localizer.text(MessageId::COLOR_FEATURES_PROFILE_CURRENT),
            saved: localizer.text(MessageId::COLOR_FEATURES_PROFILE_SAVED),
            saved_dialog: localizer.text(MessageId::COLOR_FEATURES_PROFILE_SAVED_DIALOG),
            standard: localizer.text(MessageId::COLOR_FEATURES_PROFILE_STANDARD),
            import: localizer.text(MessageId::COLOR_FEATURES_PROFILE_IMPORT),
            use_profile: localizer.text(MessageId::COLOR_FEATURES_PROFILE_USE_PROFILE),
            show: localizer.text(MessageId::COLOR_FEATURES_PROFILE_SHOW),
            hide: localizer.text(MessageId::COLOR_FEATURES_PROFILE_HIDE),
            shown: localizer.text(MessageId::COLOR_FEATURES_PROFILE_SHOWN),
            remove: localizer.text(MessageId::COLOR_FEATURES_PROFILE_REMOVE),
            embedded: localizer.text(MessageId::COLOR_FEATURES_PROFILE_EMBEDDED),
            interpret_title: localizer.text(MessageId::COLOR_FEATURES_PROFILE_INTERPRET_TITLE),
            interpret_help: localizer.text(MessageId::COLOR_FEATURES_PROFILE_INTERPRET_HELP),
            interpret_as: localizer.text(MessageId::COLOR_FEATURES_PROFILE_INTERPRET_AS),
        }
    }
}

#[derive(Clone, Serialize)]
pub struct ExportCopy {
    pub common: CommonCopy,
    pub title: Arc<str>,
    pub help: Arc<str>,
    pub export: Arc<str>,
    pub choose_file: Arc<str>,
    pub destination: Arc<str>,
    pub range: Arc<str>,
    pub clip_hdr: Arc<str>,
    pub clip_help: Arc<str>,
    pub format: Arc<str>,
    pub profile: Arc<str>,
    pub depth: Arc<str>,
    pub transparency: Arc<str>,
    pub preserve: Arc<str>,
    pub keep_transparency: Arc<str>,
    pub white_background: Arc<str>,
    pub black_background: Arc<str>,
    pub white: Arc<str>,
    pub black: Arc<str>,
    pub intent: Arc<str>,
    pub relative: Arc<str>,
    pub perceptual: Arc<str>,
    pub saturation: Arc<str>,
    pub absolute: Arc<str>,
    pub dither: Arc<str>,
    pub dither_none: Arc<str>,
    pub dither_stochastic: Arc<str>,
    pub quality: Arc<str>,
    pub pixel_size: Arc<str>,
    pub original_size: Arc<str>,
    pub fit_bounds: Arc<str>,
    pub maximum_width: Arc<str>,
    pub maximum_height: Arc<str>,
    pub enlarge: Arc<str>,
    pub resolution: Arc<str>,
    pub keep_resolution: Arc<str>,
    pub ppi: Arc<str>,
    pub omit: Arc<str>,
    pub custom: Arc<str>,
    pub metadata: Arc<str>,
    pub remove_location: Arc<str>,
    pub metadata_all: Arc<str>,
    pub metadata_copyright: Arc<str>,
    pub metadata_none: Arc<str>,
    pub metadata_exr: Arc<str>,
    pub preset: Arc<str>,
    pub preset_name: Arc<str>,
    pub save_preset: Arc<str>,
    pub update_preset: Arc<str>,
    pub delete_preset: Arc<str>,
    pub reset_destination: Arc<str>,
    pub save_new_preset: Arc<str>,
    pub update_saved_preset: Arc<str>,
    pub remove_saved_preset: Arc<str>,
    pub restore_original: Arc<str>,
    pub save_preset_help: Arc<str>,
    pub update_preset_help: Arc<str>,
    pub remove_preset_help: Arc<str>,
    pub reset_preset_help: Arc<str>,
    pub save_preset_title: Arc<str>,
    pub preset_removed: Arc<str>,
    pub preset_saved: Arc<str>,
    pub preset_reset: Arc<str>,
    pub preview_rendition: Arc<str>,
    pub hdr_preview: Arc<str>,
    pub sdr_base: Arc<str>,
    pub output_preview: Arc<str>,
    pub artwork_preview: Arc<str>,
    pub output: Arc<str>,
    pub artwork: Arc<str>,
    pub preview: Arc<str>,
    pub preparing_comparison: Arc<str>,
    pub preview_gainmap: Arc<str>,
    pub preview_exr: Arc<str>,
    pub preview_pq: Arc<str>,
    pub preview_sdr: Arc<str>,
    pub outside_range: Arc<str>,
    pub outside_gamut: Arc<str>,
    pub size: Arc<str>,
    pub image_size: Arc<str>,
    pub color_transparency: Arc<str>,
    pub presets: Arc<str>,
    pub background: Arc<str>,
    pub flatten: Arc<str>,
    pub no_flatten: Arc<str>,
    pub transparent: Arc<str>,
    pub conversion: Arc<str>,
    pub use_print_profile: Arc<str>,
    pub reduce_banding: Arc<str>,
    pub dither_gradients: Arc<str>,
    pub jpeg_note: Arc<str>,
    pub precision_note: Arc<str>,
    pub compression_note: Arc<str>,
    pub preparing: Arc<str>,
    pub exporting: Arc<str>,
    pub finishing_file: Arc<str>,
    pub writing_image: Arc<str>,
    pub no_resolution: Arc<str>,
    pub web_share: Arc<str>,
    pub wide_color: Arc<str>,
    pub further_editing: Arc<str>,
    pub further_editing_sdr: Arc<str>,
    pub print_destination: Arc<str>,
    pub depth_8: Arc<str>,
    pub depth_16: Arc<str>,
    pub depth_float32: Arc<str>,
    pub format_png: Arc<str>,
    pub format_tiff: Arc<str>,
    pub format_jpeg: Arc<str>,
    pub format_webp: Arc<str>,
    pub format_exr: Arc<str>,
    pub format_pq: Arc<str>,
    pub format_pq_clipped: Arc<str>,
    pub format_jpeg_hdr: Arc<str>,
    pub format_avif_hdr: Arc<str>,
    pub jpeg_gainmap: Arc<str>,
    pub avif_gainmap: Arc<str>,
    pub sdr_rendition: Arc<str>,
    pub hdr_native: Arc<str>,
}
impl ExportCopy {
    pub fn new(localizer: &Localizer) -> Self {
        Self { common: CommonCopy::new(localizer),
            title: localizer.text(MessageId::COLOR_FEATURES_EXPORT_TITLE),
            help: localizer.text(MessageId::COLOR_FEATURES_EXPORT_HELP),
            export: localizer.text(MessageId::COLOR_FEATURES_EXPORT_EXPORT),
            choose_file: localizer.text(MessageId::COLOR_FEATURES_EXPORT_CHOOSE_FILE),
            destination: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DESTINATION),
            range: localizer.text(MessageId::COLOR_FEATURES_EXPORT_RANGE),
            clip_hdr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_CLIP_HDR),
            clip_help: localizer.text(MessageId::COLOR_FEATURES_EXPORT_CLIP_HELP),
            format: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT),
            profile: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PROFILE),
            depth: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DEPTH),
            transparency: localizer.text(MessageId::COLOR_FEATURES_EXPORT_TRANSPARENCY),
            preserve: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESERVE),
            keep_transparency: localizer.text(MessageId::COLOR_FEATURES_EXPORT_KEEP_TRANSPARENCY),
            white_background: localizer.text(MessageId::COLOR_FEATURES_EXPORT_WHITE_BACKGROUND),
            black_background: localizer.text(MessageId::COLOR_FEATURES_EXPORT_BLACK_BACKGROUND),
            white: localizer.text(MessageId::COLOR_FEATURES_EXPORT_WHITE),
            black: localizer.text(MessageId::COLOR_FEATURES_EXPORT_BLACK),
            intent: localizer.text(MessageId::COLOR_FEATURES_EXPORT_INTENT),
            relative: localizer.text(MessageId::COLOR_FEATURES_EXPORT_RELATIVE),
            perceptual: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PERCEPTUAL),
            saturation: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SATURATION),
            absolute: localizer.text(MessageId::COLOR_FEATURES_EXPORT_ABSOLUTE),
            dither: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DITHER),
            dither_none: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DITHER_NONE),
            dither_stochastic: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DITHER_STOCHASTIC),
            quality: localizer.text(MessageId::COLOR_FEATURES_EXPORT_QUALITY),
            pixel_size: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PIXEL_SIZE),
            original_size: localizer.text(MessageId::COLOR_FEATURES_EXPORT_ORIGINAL_SIZE),
            fit_bounds: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FIT_BOUNDS),
            maximum_width: localizer.text(MessageId::COLOR_FEATURES_EXPORT_MAXIMUM_WIDTH),
            maximum_height: localizer.text(MessageId::COLOR_FEATURES_EXPORT_MAXIMUM_HEIGHT),
            enlarge: localizer.text(MessageId::COLOR_FEATURES_EXPORT_ENLARGE),
            resolution: localizer.text(MessageId::COLOR_FEATURES_EXPORT_RESOLUTION),
            keep_resolution: localizer.text(MessageId::COLOR_FEATURES_EXPORT_KEEP_RESOLUTION),
            ppi: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PPI),
            omit: localizer.text(MessageId::COLOR_FEATURES_EXPORT_OMIT),
            custom: localizer.text(MessageId::COLOR_FEATURES_EXPORT_CUSTOM),
            metadata: localizer.text(MessageId::COLOR_FEATURES_EXPORT_METADATA),
            remove_location: localizer.text(MessageId::COLOR_FEATURES_EXPORT_REMOVE_LOCATION),
            metadata_all: localizer.text(MessageId::COLOR_FEATURES_EXPORT_METADATA_ALL),
            metadata_copyright: localizer.text(MessageId::COLOR_FEATURES_EXPORT_METADATA_COPYRIGHT),
            metadata_none: localizer.text(MessageId::COLOR_FEATURES_EXPORT_METADATA_NONE),
            metadata_exr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_METADATA_EXR),
            preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESET),
            preset_name: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESET_NAME),
            save_preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SAVE_PRESET),
            update_preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_UPDATE_PRESET),
            delete_preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DELETE_PRESET),
            reset_destination: localizer.text(MessageId::COLOR_FEATURES_EXPORT_RESET_DESTINATION),
            save_new_preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SAVE_NEW_PRESET),
            update_saved_preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_UPDATE_SAVED_PRESET),
            remove_saved_preset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_REMOVE_SAVED_PRESET),
            restore_original: localizer.text(MessageId::COLOR_FEATURES_EXPORT_RESTORE_ORIGINAL),
            save_preset_help: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SAVE_PRESET_HELP),
            update_preset_help: localizer.text(MessageId::COLOR_FEATURES_EXPORT_UPDATE_PRESET_HELP),
            remove_preset_help: localizer.text(MessageId::COLOR_FEATURES_EXPORT_REMOVE_PRESET_HELP),
            reset_preset_help: localizer.text(MessageId::COLOR_FEATURES_EXPORT_RESET_PRESET_HELP),
            save_preset_title: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SAVE_PRESET_TITLE),
            preset_removed: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESET_REMOVED),
            preset_saved: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESET_SAVED),
            preset_reset: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESET_RESET),
            preview_rendition: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREVIEW_RENDITION),
            hdr_preview: localizer.text(MessageId::COLOR_FEATURES_EXPORT_HDR_PREVIEW),
            sdr_base: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SDR_BASE),
            output_preview: localizer.text(MessageId::COLOR_FEATURES_EXPORT_OUTPUT_PREVIEW),
            artwork_preview: localizer.text(MessageId::COLOR_FEATURES_EXPORT_ARTWORK_PREVIEW),
            output: localizer.text(MessageId::COLOR_FEATURES_EXPORT_OUTPUT),
            artwork: localizer.text(MessageId::COLOR_FEATURES_EXPORT_ARTWORK),
            preview: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREVIEW),
            preparing_comparison: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREPARING_COMPARISON),
            preview_gainmap: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREVIEW_GAINMAP),
            preview_exr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREVIEW_EXR),
            preview_pq: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREVIEW_PQ),
            preview_sdr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREVIEW_SDR),
            outside_range: localizer.text(MessageId::COLOR_FEATURES_EXPORT_OUTSIDE_RANGE),
            outside_gamut: localizer.text(MessageId::COLOR_FEATURES_EXPORT_OUTSIDE_GAMUT),
            size: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SIZE),
            image_size: localizer.text(MessageId::COLOR_FEATURES_EXPORT_IMAGE_SIZE),
            color_transparency: localizer.text(MessageId::COLOR_FEATURES_EXPORT_COLOR_TRANSPARENCY),
            presets: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRESETS),
            background: localizer.text(MessageId::COLOR_FEATURES_EXPORT_BACKGROUND),
            flatten: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FLATTEN),
            no_flatten: localizer.text(MessageId::COLOR_FEATURES_EXPORT_NO_FLATTEN),
            transparent: localizer.text(MessageId::COLOR_FEATURES_EXPORT_TRANSPARENT),
            conversion: localizer.text(MessageId::COLOR_FEATURES_EXPORT_CONVERSION),
            use_print_profile: localizer.text(MessageId::COLOR_FEATURES_EXPORT_USE_PRINT_PROFILE),
            reduce_banding: localizer.text(MessageId::COLOR_FEATURES_EXPORT_REDUCE_BANDING),
            dither_gradients: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DITHER_GRADIENTS),
            jpeg_note: localizer.text(MessageId::COLOR_FEATURES_EXPORT_JPEG_NOTE),
            precision_note: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRECISION_NOTE),
            compression_note: localizer.text(MessageId::COLOR_FEATURES_EXPORT_COMPRESSION_NOTE),
            preparing: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PREPARING),
            finishing_file: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FINISHING_FILE),
            writing_image: localizer.text(MessageId::COLOR_FEATURES_EXPORT_WRITING_IMAGE),
            exporting: localizer.text(MessageId::COLOR_FEATURES_EXPORT_EXPORTING),
            no_resolution: localizer.text(MessageId::COLOR_FEATURES_EXPORT_NO_RESOLUTION),
            web_share: localizer.text(MessageId::COLOR_FEATURES_EXPORT_WEB_SHARE),
            wide_color: localizer.text(MessageId::COLOR_FEATURES_EXPORT_WIDE_COLOR),
            further_editing: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FURTHER_EDITING),
            further_editing_sdr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FURTHER_EDITING_SDR),
            print_destination: localizer.text(MessageId::COLOR_FEATURES_EXPORT_PRINT_DESTINATION),
            depth_8: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DEPTH_8),
            depth_16: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DEPTH_16),
            depth_float32: localizer.text(MessageId::COLOR_FEATURES_EXPORT_DEPTH_FLOAT32),
            format_png: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_PNG),
            format_tiff: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_TIFF),
            format_jpeg: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_JPEG),
            format_webp: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_WEBP),
            format_exr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_EXR),
            format_pq: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_PQ),
            format_pq_clipped: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_PQ_CLIPPED),
            format_jpeg_hdr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_JPEG_HDR),
            format_avif_hdr: localizer.text(MessageId::COLOR_FEATURES_EXPORT_FORMAT_AVIF_HDR),
            jpeg_gainmap: localizer.text(MessageId::COLOR_FEATURES_EXPORT_JPEG_GAINMAP),
            avif_gainmap: localizer.text(MessageId::COLOR_FEATURES_EXPORT_AVIF_GAINMAP),
            sdr_rendition: localizer.text(MessageId::COLOR_FEATURES_EXPORT_SDR_RENDITION),
            hdr_native: localizer.text(MessageId::COLOR_FEATURES_EXPORT_HDR_NATIVE),
        }
    }
}

#[derive(Clone, Serialize)]
pub struct DocumentColorCopy {
    pub common: CommonCopy,
    pub assign_title: Arc<str>,
    pub convert_title: Arc<str>,
    pub depth_title: Arc<str>,
    pub repair_title: Arc<str>,
    pub rasterize_title: Arc<str>,
    pub undo_title: Arc<str>,
    pub redo_title: Arc<str>,
    pub assign_help: Arc<str>,
    pub depth_help: Arc<str>,
    pub convert_help: Arc<str>,
    pub rasterize_help: Arc<str>,
    pub repair_help: Arc<str>,
    pub correct_profile: Arc<str>,
    pub space: Arc<str>,
    pub depth: Arc<str>,
    pub depth_8: Arc<str>,
    pub depth_16: Arc<str>,
    pub depth_float16: Arc<str>,
    pub depth_float32: Arc<str>,
    pub dither: Arc<str>,
    pub dither_stochastic: Arc<str>,
    pub result: Arc<str>,
    pub editable_layers: Arc<str>,
    pub flattened_copy: Arc<str>,
    pub rasterize: Arc<str>,
    pub apply_profile: Arc<str>,
    pub preview_help: Arc<str>,
    pub preparing: Arc<str>,
    pub before: Arc<str>,
    pub after: Arc<str>,
    pub prepared_composition: Arc<str>,
    pub original_composition: Arc<str>,
    pub outside_gamut: Arc<str>,
    pub composition_preview: Arc<str>,
    pub adds_layer: Arc<str>,
    pub add_source: Arc<str>,
    pub save_copy: Arc<str>,
    pub preview: Arc<str>,
    pub preparing_comparison: Arc<str>,
    pub choose_different: Arc<str>,
    pub clipped_comparison: Arc<str>,
    pub layered_open: Arc<str>,
    pub compare_before_apply: Arc<str>,
    pub choose_destination: Arc<str>,
    pub convert_layers: Arc<str>,
    pub create_flattened: Arc<str>,
    pub assign_native_help: Arc<str>,
    pub convert_native_help: Arc<str>,
    pub depth_native_help: Arc<str>,
    pub create_copy: Arc<str>,
    pub preparing_title: Arc<str>,
    pub preparing_help: Arc<str>,
    pub current_source: Arc<str>,
    pub source_baked_help: Arc<str>,
    pub source_native_help: Arc<str>,
    pub choose_valid_profile: Arc<str>,
    pub rasterizing: Arc<str>,
    pub rasterize_comparison: Arc<str>,
    pub source_clipped: Arc<str>,
    pub rasterize_compare: Arc<str>,
}
impl DocumentColorCopy {
    pub fn new(localizer: &Localizer) -> Self {
        Self { common: CommonCopy::new(localizer),
            preparing_comparison: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREPARING_COMPARISON),
            choose_different: localizer.text(MessageId::COLOR_FEATURES_COLOR_CHOOSE_DIFFERENT),
            clipped_comparison: localizer.text(MessageId::COLOR_FEATURES_COLOR_CLIPPED_COMPARISON),
            layered_open: localizer.text(MessageId::COLOR_FEATURES_COLOR_LAYERED_OPEN),
            compare_before_apply: localizer.text(MessageId::COLOR_FEATURES_COLOR_COMPARE_BEFORE_APPLY),
            choose_destination: localizer.text(MessageId::COLOR_FEATURES_COLOR_CHOOSE_DESTINATION),
            convert_layers: localizer.text(MessageId::COLOR_FEATURES_COLOR_CONVERT_LAYERS),
            create_flattened: localizer.text(MessageId::COLOR_FEATURES_COLOR_CREATE_FLATTENED),
            assign_native_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_ASSIGN_NATIVE_HELP),
            convert_native_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_CONVERT_NATIVE_HELP),
            depth_native_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_NATIVE_HELP),
            create_copy: localizer.text(MessageId::COLOR_FEATURES_COLOR_CREATE_COPY),
            preparing_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREPARING_TITLE),
            preparing_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREPARING_HELP),
            current_source: localizer.text(MessageId::COLOR_FEATURES_COLOR_CURRENT_SOURCE),
            source_baked_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_SOURCE_BAKED_HELP),
            source_native_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_SOURCE_NATIVE_HELP),
            choose_valid_profile: localizer.text(MessageId::COLOR_FEATURES_COLOR_CHOOSE_VALID_PROFILE),
            rasterizing: localizer.text(MessageId::COLOR_FEATURES_COLOR_RASTERIZING),
            rasterize_comparison: localizer.text(MessageId::COLOR_FEATURES_COLOR_RASTERIZE_COMPARISON),
            source_clipped: localizer.text(MessageId::COLOR_FEATURES_COLOR_SOURCE_CLIPPED),
            rasterize_compare: localizer.text(MessageId::COLOR_FEATURES_COLOR_RASTERIZE_COMPARE),

            assign_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_ASSIGN_TITLE),
            convert_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_CONVERT_TITLE),
            depth_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_TITLE),
            repair_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_REPAIR_TITLE),
            rasterize_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_RASTERIZE_TITLE),
            undo_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_UNDO_TITLE),
            redo_title: localizer.text(MessageId::COLOR_FEATURES_COLOR_REDO_TITLE),
            assign_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_ASSIGN_HELP),
            depth_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_HELP),
            convert_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_CONVERT_HELP),
            rasterize_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_RASTERIZE_HELP),
            repair_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_REPAIR_HELP),
            correct_profile: localizer.text(MessageId::COLOR_FEATURES_COLOR_CORRECT_PROFILE),
            space: localizer.text(MessageId::COLOR_FEATURES_COLOR_SPACE),
            depth: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH),
            depth_8: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_8),
            depth_16: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_16),
            depth_float16: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_FLOAT16),
            depth_float32: localizer.text(MessageId::COLOR_FEATURES_COLOR_DEPTH_FLOAT32),
            dither: localizer.text(MessageId::COLOR_FEATURES_COLOR_DITHER),
            dither_stochastic: localizer.text(MessageId::COLOR_FEATURES_COLOR_DITHER_STOCHASTIC),
            result: localizer.text(MessageId::COLOR_FEATURES_COLOR_RESULT),
            editable_layers: localizer.text(MessageId::COLOR_FEATURES_COLOR_EDITABLE_LAYERS),
            flattened_copy: localizer.text(MessageId::COLOR_FEATURES_COLOR_FLATTENED_COPY),
            rasterize: localizer.text(MessageId::COLOR_FEATURES_COLOR_RASTERIZE),
            apply_profile: localizer.text(MessageId::COLOR_FEATURES_COLOR_APPLY_PROFILE),
            preview_help: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREVIEW_HELP),
            preparing: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREPARING),
            before: localizer.text(MessageId::COLOR_FEATURES_COLOR_BEFORE),
            after: localizer.text(MessageId::COLOR_FEATURES_COLOR_AFTER),
            prepared_composition: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREPARED_COMPOSITION),
            original_composition: localizer.text(MessageId::COLOR_FEATURES_COLOR_ORIGINAL_COMPOSITION),
            outside_gamut: localizer.text(MessageId::COLOR_FEATURES_COLOR_OUTSIDE_GAMUT),
            composition_preview: localizer.text(MessageId::COLOR_FEATURES_COLOR_COMPOSITION_PREVIEW),
            adds_layer: localizer.text(MessageId::COLOR_FEATURES_COLOR_ADDS_LAYER),
            add_source: localizer.text(MessageId::COLOR_FEATURES_COLOR_ADD_SOURCE),
            save_copy: localizer.text(MessageId::COLOR_FEATURES_COLOR_SAVE_COPY),
            preview: localizer.text(MessageId::COLOR_FEATURES_COLOR_PREVIEW),
        }
    }
}

pub fn proof_status(localizer: &Localizer, name: &str, proof: bool, gamut: bool) -> String {
    let mut args = FluentArgs::new(); args.set("name", name); args.set("gamut", if gamut {"enabled"} else {"disabled"});
    localizer.format(if proof {MessageId::COLOR_FEATURES_PROOF_STATUS} else {MessageId::COLOR_FEATURES_GAMUT_STATUS}, &args)
}
pub fn named(localizer: &Localizer, message: MessageId, name: &str) -> String {
    let mut args = FluentArgs::new(); args.set("name", name); localizer.format(message, &args)
}

pub fn export_preview_status(localizer: &Localizer, format: crate::ExportFormat, gainmap: bool, clipped: bool) -> String {
    let preview = localizer.text(if gainmap {MessageId::COLOR_FEATURES_EXPORT_PREVIEW_GAINMAP}
        else if format == crate::ExportFormat::Exr {MessageId::COLOR_FEATURES_EXPORT_PREVIEW_EXR}
        else if matches!(format, crate::ExportFormat::PngHdr | crate::ExportFormat::PngHdrMapped) {MessageId::COLOR_FEATURES_EXPORT_PREVIEW_PQ}
        else {MessageId::COLOR_FEATURES_EXPORT_PREVIEW_SDR});
    let warning = if !clipped {Arc::from("")} else {localizer.text(if matches!(format, crate::ExportFormat::PngHdr | crate::ExportFormat::JpegHdr | crate::ExportFormat::AvifHdr) {
        MessageId::COLOR_FEATURES_EXPORT_OUTSIDE_RANGE } else { MessageId::COLOR_FEATURES_EXPORT_OUTSIDE_GAMUT })};
    let mut args = FluentArgs::new(); args.set("preview", preview.as_ref()); args.set("warning", warning.as_ref());
    localizer.format(MessageId::COLOR_FEATURES_EXPORT_PREVIEW_SUMMARY, &args)
}

pub fn profile_unavailable(localizer: &Localizer, id: &str) -> String {
    let mut args = FluentArgs::new(); args.set("id", id); localizer.format(MessageId::COLOR_FEATURES_PROFILE_UNAVAILABLE, &args)
}
pub fn profile_visibility(localizer: &Localizer, channels: Option<layer_core::color::ProfileChannels>, visible: bool) -> String {
    let channels: Arc<str> = match channels { Some(layer_core::color::ProfileChannels::Rgb) => Arc::from("RGB"),
        Some(layer_core::color::ProfileChannels::Cmyk) => Arc::from("CMYK"),
        Some(layer_core::color::ProfileChannels::Gray) => localizer.text(MessageId::COLOR_FEATURES_PROFILE_GRAYSCALE), None => Arc::from("") };
    if visible { return channels.to_string(); }
    let mut args = FluentArgs::new(); args.set("channels", channels.as_ref()); localizer.format(MessageId::COLOR_FEATURES_PROFILE_HIDDEN, &args)
}

pub fn proof_dial_value(recipe: layer_core::color::hdr::SdrRendition, localizer: &Localizer) -> String {
    let balance = localizer.text(MessageId::COLOR_FEATURES_PROOF_BALANCE);
    let contrast = localizer.text(MessageId::COLOR_FEATURES_PROOF_CONTRAST);
    format!("{} {:+.0}%, {} {:.0}%", balance, recipe.balance * 100., contrast, recipe.contrast * 100.)
}

#[derive(Clone, Serialize)]
pub struct ComparisonCopy {
    pub before: Arc<str>,
    pub after: Arc<str>,
    pub master: Arc<str>,
    pub output: Arc<str>,
    pub choose_profile: Arc<str>,
    pub rendering: Arc<str>,
    pub sdr_fallback: Arc<str>,
    pub hdr_output: Arc<str>,
    pub hdr_sdr_display: Arc<str>,
    pub hdr_master: Arc<str>,
    pub master_sdr: Arc<str>,
    pub output_sdr: Arc<str>,
    pub sdr_output: Arc<str>,
    pub outside_hdr: Arc<str>,
    pub hdr_checked: Arc<str>,
    pub hdr_clipped: Arc<str>,
    pub output_preview: Arc<str>,
    pub output_gamut: Arc<str>,
    pub complete_canvas: Arc<str>,
    pub hdr_view: Arc<str>,
}
impl ComparisonCopy {
    pub fn new(localizer: &Localizer) -> Self {
        Self {
            before: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_BEFORE),
            after: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_AFTER),
            master: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_MASTER),
            output: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_OUTPUT),
            choose_profile: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_CHOOSE_PROFILE),
            rendering: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_RENDERING),
            sdr_fallback: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_SDR_FALLBACK),
            hdr_output: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_HDR_OUTPUT),
            hdr_sdr_display: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_HDR_SDR_DISPLAY),
            hdr_master: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_HDR_MASTER),
            master_sdr: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_MASTER_SDR),
            output_sdr: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_OUTPUT_SDR),
            sdr_output: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_SDR_OUTPUT),
            outside_hdr: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_OUTSIDE_HDR),
            hdr_checked: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_HDR_CHECKED),
            hdr_clipped: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_HDR_CLIPPED),
            output_preview: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_OUTPUT_PREVIEW),
            output_gamut: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_OUTPUT_GAMUT),
            complete_canvas: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_COMPLETE_CANVAS),
            hdr_view: localizer.text(MessageId::COLOR_FEATURES_COMPARISON_HDR_VIEW),
        }
    }
}
