[package]
name = "layer-windows-link"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "layer_windows"
crate-type = ["cdylib"]

[features]
release-identity = ["layer-windows/release-identity"]
software-adapter-tests = ["layer-windows/software-adapter-tests"]

[dependencies]
layer-windows = { path = ".." }
