// Original premultiplied layer pixels are immutable for the whole transaction.
// Sample color * selection together, never filter them independently (halos).
// Rows x, y and w map a destination pixel to homogeneous source coordinates.
// attachment holds its origin in layer pixels, the flags and the background.
struct Transform { x:vec4<f32>, y:vec4<f32>, w:vec4<f32>, attachment:vec4<f32> }
override scalar:bool=false;
override visibility:bool=false;
@group(0) @binding(0) var<uniform> transform:Transform;
// Bounded source views and source_info are generated by the host.
// group 1, binding 17 and brush_selection_at come from selection_clip.wgsl.
const FILTERED=1u;
const UNMOVED=2u;
const PLACEMENT=4u;
const BICUBIC=8u;
const NO_VIEW=16u;

@vertex fn vertex_main(@builtin(vertex_index) index:u32)->@builtin(position) vec4<f32> {
    let p=array<vec2<f32>,3>(vec2(-1.,-1.),vec2(3.,-1.),vec2(-1.,3.));
    return vec4(p[index],0.,1.);
}
fn flags()->u32 {return u32(transform.attachment.z);}
fn background()->f32 {return transform.attachment.w;}
fn original(p:vec2<i32>)->vec4<f32> {
    if any(p<source_info.bounds.xy) || any(p>=source_info.bounds.xy+source_info.bounds.zw) {return vec4(background());}
    for (var i=0u;i<16u;i++) {
        let view=source_info.views[i];
        let local=p-view.xy;
        if all(local>=vec2(0)) && all(local<view.zw) {
            let color=source_load(i,local);
            if scalar {return vec4(color.r);}
            return color;
        }
    }
    return vec4(background());
}
fn covered(value:vec4<f32>,p:vec2<i32>)->vec4<f32> {
    var v=value;
    if visibility {v.a=1.;}
    return v*brush_selection_at(vec2<f32>(p)+vec2(.5));
}
fn selected(p:vec2<i32>)->vec4<f32> {return covered(original(p),p);}
// The one view holding every texel from low to high inclusive, inside the
// source bounds, or NO_VIEW. Blocks inside one view skip the per-texel search.
fn view_of(low:vec2<i32>,high:vec2<i32>)->u32 {
    if any(low<source_info.bounds.xy) || any(high>=source_info.bounds.xy+source_info.bounds.zw) {return NO_VIEW;}
    for (var i=0u;i<16u;i++) {
        let view=source_info.views[i];
        if all(low>=view.xy) && all(high<view.xy+view.zw) {return i;}
    }
    return NO_VIEW;
}
fn tap(view:u32,p:vec2<i32>)->vec4<f32> {
    if view==NO_VIEW {return selected(p);}
    var color=source_load(view,p-source_info.views[view].xy);
    if scalar {color=vec4(color.r);}
    return covered(color,p);
}
// A pixel whose source lies beyond the horizon, or beyond the finite source.
fn outside(selection:f32)->vec4<f32> {
    if (flags()&PLACEMENT)!=0u {return vec4(background());}
    if visibility {return vec4(vec3(background()),1.)*selection;}
    return vec4(0.);
}
fn beyond_horizon()->vec4<f32> {
    return outside(select(0.,1.,brush_selection.info.y==0u || brush_selection.info.x!=0u));
}
// Test before float->integer conversion; arbitrarily distant transforms
// never create out-of-range integer coordinates or repeat edge texels.
fn far(local:vec2<f32>,margin:f32)->bool {
    return any(local<vec2<f32>(source_info.bounds.xy)-margin)
        || any(local>vec2<f32>(source_info.bounds.xy+source_info.bounds.zw)+margin);
}
fn nearest(local:vec2<f32>)->vec4<f32> {
    if far(local,.5) {return outside(brush_selection_at(local));}
    return selected(vec2<i32>(floor(local)));
}
fn bilinear(local:vec2<f32>)->vec4<f32> {
    if far(local,.5) {return outside(brush_selection_at(local));}
    let p=local-vec2(.5);let base=vec2<i32>(floor(p));let t=fract(p);
    let view=view_of(base,base+vec2(1));
    return mix(mix(tap(view,base),tap(view,base+vec2(1,0)),t.x),
        mix(tap(view,base+vec2(0,1)),tap(view,base+vec2(1,1)),t.x),t.y);
}
fn catmull_rom(t:f32)->vec4<f32> {
    let t2=t*t;let t3=t2*t;
    return vec4(-.5*t3+t2-.5*t,1.5*t3-2.5*t2+1.,-1.5*t3+2.*t2+.5*t,.5*t3-.5*t2);
}
// Catmull-Rom with overshoot clamped to the nearest four taps, whose brightest
// straight color also bounds the result's.
fn bicubic(local:vec2<f32>)->vec4<f32> {
    if far(local,2.) {return outside(brush_selection_at(local));}
    let p=local-vec2(.5);let base=vec2<i32>(floor(p));let t=fract(p);
    let wx=catmull_rom(t.x);let wy=catmull_rom(t.y);
    let view=view_of(base-vec2(1),base+vec2(2));
    var sum=vec4(0.);var low=vec4(3.4e38);var high=vec4(-3.4e38);var brightest=vec3(0.);
    for (var j=0;j<4;j++) {
        var row=vec4(0.);
        for (var i=0;i<4;i++) {
            let value=tap(view,base+vec2(i-1,j-1));
            row+=value*wx[i];
            if (i==1 || i==2) && (j==1 || j==2) {
                low=min(low,value);high=max(high,value);
                if value.a>0. {brightest=max(brightest,value.rgb/value.a);}
            }
        }
        sum+=row*wy[j];
    }
    var value=clamp(sum,low,high);
    if scalar {return clamp(value,vec4(0.),vec4(1.));}
    value.a=clamp(value.a,0.,1.);
    return vec4(min(value.rgb,value.a*brightest),value.a);
}
fn source_position(world:vec2<f32>)->vec3<f32> {
    let h=vec3(world,1.);
    let w=dot(transform.w.xyz,h);
    return vec3(vec2(dot(transform.x.xyz,h),dot(transform.y.xyz,h))/w,w);
}
fn bilinear_at(world:vec2<f32>)->vec4<f32> {
    let s=source_position(world);
    if s.z<=0. {return beyond_horizon();}
    return bilinear(s.xy);
}
// Destination pixels covering several source pixels average a grid of up to
// 4x4 bilinear taps spread over the pixel, sized by the local Jacobian.
fn minified(world:vec2<f32>,count:vec2<u32>)->vec4<f32> {
    var sum=vec4(0.);
    for (var j=0u;j<count.y;j++) {
        for (var i=0u;i<count.x;i++) {
            sum+=bilinear_at(world+(vec2(f32(i),f32(j))+.5)/vec2<f32>(count)-.5);
        }
    }
    return sum/f32(count.x*count.y);
}
fn transformed(world:vec2<f32>)->vec4<f32> {
    let s=source_position(world);
    if s.z<=0. {return beyond_horizon();}
    if (flags()&FILTERED)==0u {return nearest(s.xy);}
    let dx=(transform.x.xy-s.x*transform.w.xy)/s.z;
    let dy=(transform.y.xy-s.y*transform.w.xy)/s.z;
    let reach=vec2(length(vec2(dx.x,dy.x)),length(vec2(dx.y,dy.y)));
    let count=vec2<u32>(clamp(floor(reach+.5),vec2(1.),vec2(4.)));
    if any(count>vec2(1u)) {return minified(world,count);}
    if (flags()&BICUBIC)!=0u {return bicubic(s.xy);}
    return bilinear(s.xy);
}
@fragment fn fragment_main(@builtin(position) position:vec4<f32>)->@location(0) vec4<f32> {
    let world=position.xy+transform.attachment.xy;
    let base=original(vec2<i32>(floor(world)));
    // Exact no-op must not cut and recomposite fractional selection coverage.
    if (flags()&UNMOVED)!=0u {return base;}
    let moved=transformed(world);
    if (flags()&PLACEMENT)!=0u {return moved;}
    if visibility {
        let remainder=mix(base.r,background(),brush_selection_at(world));
        return vec4(moved.r+remainder*(1.-moved.a));
    }
    let remainder=base*(1.-brush_selection_at(world));
    if scalar {return max(moved,remainder);}
    return moved+remainder*(1.-moved.a);
}
