import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';

// Production DOM, shared sampling and GPU loupe. CDP preserves pointer kinds;
// device performance additionally uses Android's OS stylus injector.
export async function checkColorPicker({call,evaluate,settle}) {
  const output=process.env.LAYER_TEST_ARTIFACTS||'artifacts/color-picker/web';await mkdir(output,{recursive:true});
  const send=async action=>{await evaluate(`layerApp.dispatch(${JSON.stringify(action)})`);await settle();};
  const invoke=command=>send({type:'invoke',command});
  const wait=expression=>evaluate(`new Promise((resolve,reject)=>{const end=performance.now()+15000;function check(){if(${expression})resolve();else if(performance.now()>end)reject(Error(${JSON.stringify(expression)}));else setTimeout(check,20)}check()})`);
  const state=()=>evaluate('JSON.parse(JSON.stringify(layerApp.state(),(_,v)=>typeof v==="bigint"?Number(v):v))');
  const shot=async name=>{const png=await call('Page.captureScreenshot',{format:'png'});await writeFile(`${output}/${name}.png`,Buffer.from(png.data,'base64'));};
  const mouse=async(type,point,device='pen',buttons=0)=>call('Input.dispatchMouseEvent',{type,...point,pointerType:device,button:type==='mouseMoved'?'none':'left',buttons,clickCount:1,force:buttons?.7:0});
  const tap=async(point,device='mouse')=>{await mouse('mousePressed',point,device,1);await mouse('mouseReleased',point,device);};
  const rect=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect().toJSON()`);
  const buttonPoint=async selector=>{const b=await rect(selector);return{x:b.x+b.width/2,y:b.y+b.height/2};};
  await evaluate(`layerApp.app.workspace_input(JSON.stringify({type:'switch',id:'builtin:workspace:painter'}));null`);
  await wait(`JSON.parse(layerApp.app.workspace_view()).id==='builtin:workspace:painter'&&!JSON.parse(layerApp.app.workspace_view()).busy`);await settle();
  await invoke('brush');await invoke('fit_canvas');
  const picker='button[aria-label="Color Picker"]';
  const tile=await buttonPoint(picker);
  const order=await evaluate(`(()=>{const layout=layerApp.state().workspace.layout;return layout.panels.find(p=>p.content.tiles?.some(t=>t.control.kind==='brush_size_slider')).content.tiles.map(t=>t.control.kind==='command'?t.control.command:t.control.kind)})()`);
  assert.deepEqual(order,['brush_size_slider','color_picker','brush_opacity_slider','undo','redo']);
  await tap(tile);await settle();assert.equal((await state()).layer_tools.tool,'pick_visible');
  await tap(tile);await settle();
  await wait('layerApp.state().customization.drawer?.compact');
  assert.deepEqual((await state()).customization.drawer.columns,[['tool_settings']]);
  assert.equal((await state()).customization.drawer.dismissal,'explicit');
  const sizes=await evaluate(`[...document.querySelector('[data-picker-setting="Sample size"]').options].map(o=>Number(o.value))`);
  assert.deepEqual(sizes,[1,5,15,51,101]);
  await evaluate(`(()=>{const n=document.querySelector('[data-picker-setting="Sample size"]');n.value='101';n.dispatchEvent(new Event('change',{bubbles:true}));})()`);await settle();
  assert.equal((await state()).color_picker.sample_width,101);
  await shot('sketch-settings');
  await invoke('eyedropper');await send({type:'set_color_sample_size',width:1});
  const point=await evaluate(`(()=>{const c=layerApp.app.camera(),r=layerApp.canvas.getBoundingClientRect(),a=c.work_area;return{x:r.x+(a[0]+a[2]/2)*r.width/c.viewport[0],y:r.y+(a[1]+a[3]/2)*r.height/c.viewport[1]}})()`);
  await send({type:'select_brush',id:1});await send({type:'set_brush_size',value:60});await send({type:'set_color',rgba:[1,0,0,1]});
  await tap(point,'pen');await settle();
  await send({type:'set_color',rgba:[0,1,0,1]});const original=(await state()).colors;
  await invoke('eyedropper');await mouse('mouseMoved',point);await wait('layerApp.state().color_picker.preview!=null');
  assert.deepEqual((await state()).colors,original,'hover is reversible');
  assert.ok((await state()).color_picker.preview.rgba[0]>.8,'sample real red paint');
  await shot('glass-hover');
  await mouse('mousePressed',point,'pen',1);await settle();assert.deepEqual((await state()).colors,original,'pen down does not accept');
  await mouse('mouseReleased',point);await wait('layerApp.state().layer_tools.tool==="paint"');
  assert.ok((await state()).colors.foreground.rgba[0]>.8,'pen lift accepts');
  await send({type:'set_color',rgba:[0,1,0,1]});
  const contact={x:point.x,y:point.y+44};
  await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...contact}]});
  await wait('layerApp.state().color_picker.preview!=null');
  assert.ok((await state()).color_picker.preview.rgba[0]>.8,'touch samples crosshair above the finger');
  await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...contact},{id:2,x:contact.x+100,y:contact.y}]});await settle();
  assert.equal((await state()).color_picker.layer,true,'second finger toggles source');await shot('glass-layer-touch');
  await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[{id:1,...contact}]});
  await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait('layerApp.state().layer_tools.tool==="paint"');
  await invoke('eyedropper');await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,...point}]});await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();
  assert.equal((await state()).layer_tools.tool,'paint','finger tap cancels button picker');
  await send({type:'color_picker',action:{kind:'source',layer:false}});
  await send({type:'move_panel',panel:'color',target:{kind:'float',position:[30,70]}});
  await invoke('eyedropper');await mouse('mouseMoved',point);await wait('layerApp.state().color_picker.preview!=null');
  await evaluate(`window.pickerCounts={fields:0,models:0};for(const [method,key] of [['color_field_pixels','fields'],['state_update','models']]){const old=layerApp.app[method].bind(layerApp.app);layerApp.app[method]=(...args)=>{pickerCounts[key]++;return old(...args)}}`);
  for(let i=0;i<45;i++){await mouse('mouseMoved',{x:point.x-70+i*3,y:point.y});await new Promise(r=>setTimeout(r,8));}
  await settle();assert.deepEqual(await evaluate('pickerCounts'),{fields:0,models:0},'hover never synchronously rasterizes fields or rebuilds workspace');
  await shot('wheel-preview');
  await invoke('eyedropper');
  await evaluate(`layerApp.app.workspace_input(JSON.stringify({type:'switch',id:'builtin:workspace:illustrator'}));null`);
  await wait(`JSON.parse(layerApp.app.workspace_view()).id==='builtin:workspace:illustrator'&&!JSON.parse(layerApp.app.workspace_view()).busy`);await settle();
  const category=await buttonPoint('button[data-command="eyedropper"]');await tap(category);await settle();await tap(category);await settle();
  assert.deepEqual((await state()).customization.drawer.columns,[['tools'],['tool_settings']]);
  await send({type:'color_picker',action:{kind:'style',style:'eyedropper'}});await shot('paint-eyedropper-options');
  await invoke('eyedropper');
  console.log('PASS: picker tiles, settings, real sampling, pen lift, touch offset/source/cancel, retained asynchronous wheel preview and category drawer');
}
