import assert from "node:assert/strict";
import {mkdir,writeFile} from "node:fs/promises";
export async function checkEditor({call,evaluate,settle,canvasPixels}) {
  const wait=condition=>evaluate(`new Promise((resolve,reject)=>{const start=performance.now();function check(){if(${condition})resolve(true);else if(performance.now()-start>25000)reject(Error("Timed out: "+${JSON.stringify(condition)}+"; "+document.querySelector("#status").textContent));else setTimeout(check,40);}check();})`);
  const click=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await settle();};
  const invoke=async id=>{await evaluate(`layerApp.dispatch({type:"invoke",command:${JSON.stringify(id)}})`);await settle();};
  const show=async panel=>{
    await evaluate(`(()=>{const group=layerApp.app.layout(innerWidth,innerHeight).groups.find(g=>g.panels.includes("${panel}"));if(group.active!=="${panel}")layerApp.dispatch({type:"select_panel_tab",group:group.id,panel:"${panel}"});})()`);await settle();
  };
  const pointer=async(selector,fx,fy,move)=>{
    const p=await evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width*${fx},y:r.y+r.height*${fy}}})()`);
    for(const [type,x,y,buttons]of [["mousePressed",p.x,p.y,1],...(move?[["mouseMoved",p.x+move[0],p.y+move[1],1]]:[]),["mouseReleased",p.x+(move?.[0]||0),p.y+(move?.[1]||0),0]])await call("Input.dispatchMouseEvent",{type,x,y,button:"left",buttons,clickCount:1});
    await settle();
  };
  await invoke("reset_layout");
  if(await evaluate("layerApp.state().workspace.zen_mode"))await invoke("zen_mode");
  console.log("editor startup",await evaluate('layerApp.startupTimes'));
  await wait('layerApp.startupTimes.complete!==null');
  assert.equal(await evaluate('document.querySelectorAll(".header-menu").length'),8);
  assert.ok(await evaluate('!!document.querySelector(".commands-panel .tile-button")'));
  assert.ok((await canvasPixels()).white>10000);
  for(let i=0;i<4;i++)await invoke("zoom_in");
  const middle=await evaluate("Math.floor(innerWidth/2)");
  const header=await call("Page.captureScreenshot",{format:"png",fromSurface:true,clip:{x:middle,y:2,width:1,height:1,scale:1}});
  const headerPixel=await evaluate(`(async()=>{const image=new Image();image.src='data:image/png;base64,'+${JSON.stringify(header.data)};await image.decode();const c=document.createElement('canvas');c.width=c.height=1;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0);return [...ctx.getImageData(0,0,1,1).data];})()`);
  assert.deepEqual(headerPixel,[255,255,255,255],"Zoomed paper must composite through empty header space");
  await invoke("fit_canvas");
  await invoke("fill");
  assert.ok(await evaluate('layerApp.state().tool_settings.some(f=>f.id.includes("gap"))'),"Fill exposes gap controls");
  assert.ok(await evaluate('!!document.querySelector(".tool-settings-control [data-tool-setting]")'));
  await invoke("auto_select");
  assert.ok(await evaluate('layerApp.state().tool_settings.some(f=>f.id.includes("gap"))'),"Auto Select exposes gap controls");
  await invoke("brush");
  await show("color");
  const before=await evaluate('layerApp.state().brush.color');
  await pointer(".dock-group .color-wheel",.95,.5);
  await pointer(".dock-group .color-wheel",.6,.4);
  assert.notDeepEqual(await evaluate('layerApp.state().brush.color'),before,"Color wheel changes paint");
  await click(".dock-group .color-space");
  assert.equal(await evaluate('layerApp.state().colors.space'),"hls");
  await pointer(".dock-group .color-wheel",.6,.5);
  await click('.dock-group [data-color-slot="transparent"]');
  assert.equal(await evaluate('layerApp.state().colors.slot'),"transparent");
  await click('.dock-group [data-color-slot="foreground"]');
  console.log("color/tool controls passed");
  assert.ok(await evaluate('(()=>{const c=document.querySelector(".dock-group .color-wheel");return c.getContext("2d").getImageData(0,0,c.width,c.height).data.filter((v,i)=>i%4===3&&v>0).length>1000;})()'),"Color wheel contains rendered pixels");
  await show("navigator");
  assert.ok(await evaluate(`([...document.querySelectorAll('.dock-group [data-navigator-command]')].every(button=>{
    const r=button.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);
    return r.width>0&&r.height>0&&r.top>=0&&r.bottom<=innerHeight&&button.contains(hit);
  }))`),"Every Navigator command must have an unobscured hit target in the default panel");
  const zoom=await evaluate('layerApp.state().camera.zoom');
  await pointer('.dock-group [data-navigator-command="zoom_in"]',.5,.5);
  assert.ok(await evaluate('layerApp.state().camera.zoom')>zoom);
  await pointer('.dock-group [data-navigator-command="flip_horizontal"]',.5,.5);
  assert.equal(await evaluate('document.querySelector(\'.dock-group [data-navigator-command="flip_horizontal"]\').getAttribute("aria-pressed")'),"true");
  await pointer('.dock-group [data-navigator-command="flip_horizontal"]',.5,.5);
  const pan=await evaluate('layerApp.state().camera.translation');
  await pointer(".dock-group .navigator-overview",.5,.5,[20,10]);
  assert.notDeepEqual(await evaluate('layerApp.state().camera.translation'),pan,"Navigator moves the camera");
  assert.ok(await evaluate('!!document.querySelector(".navigator-surface")'),"Navigator uses a native GPU surface");
  await evaluate('window.editorWorkspace=layerApp.app.workspace_persistence(); window.editorSettings=layerApp.state().settings; layerApp.dispatch({type:"restore_settings",settings:{...editorSettings,total_zen:false}})');
  await invoke("zen_mode");
  await evaluate('window.dispatchEvent(new PointerEvent("pointermove",{clientX:innerWidth/2,clientY:innerHeight/2,pointerType:"mouse",bubbles:true}))');
  await settle();
  assert.ok(await evaluate('document.querySelector("#workspace").classList.contains("zen-hidden")'));
  assert.ok(await evaluate('[...document.querySelectorAll(".zen-toolbar")].some(n=>n.getClientRects().length)'),"Partial Zen retains edge toolbars");
  // Activate the shared tile action through the projected DOM toolbar.
  assert.ok(await evaluate('document.querySelectorAll(".zen-toolbar .tile-button button").length>3'));
  await invoke("zen_mode");
  await evaluate(`(()=>{const group=layerApp.app.layout(innerWidth,innerHeight).groups.find(g=>g.panels.includes("navigator"));window.editorColumnGroup=group.id;layerApp.dispatch({type:"customize",action:{type:"set_column_collapsed",group:group.id,collapsed:true}});})()`);
  await settle();
  await click('.collapsed-column [data-panel="navigator"]');
  await wait('!!document.querySelector(".content-drawer .navigator-overview")');
  await settle();
  await wait('document.querySelector(".content-drawer")?.getBoundingClientRect().width>=271');

  await click('.content-drawer [data-navigator-command="zoom_out"]');
  await pointer("#canvas",.5,.5);
  assert.ok(await evaluate('!!document.querySelector(".content-drawer")'),"Column drawers remain open while drawing");
  await click('.collapsed-column [data-panel="navigator"]');
  await wait('!document.querySelector(".content-drawer")');
  await click(".column-expand");
  await settle();
  assert.equal(await evaluate('layerApp.state().workspace.layout.collapsed.length'),0);
  await evaluate('(()=>{const send=action=>layerApp.dispatch({type:"customize",action});send({type:"insert_tools",panel:"toolbar",before:1});send({type:"picker_select",control:{kind:"divider"},selected:true});send({type:"picker_select",control:{kind:"panel",panel:"color"},selected:true});send({type:"confirm_tools"});window.editorDrawerTile=layerApp.state().workspace.layout.panels.find(p=>p.id==="toolbar").content.tiles.find(t=>t.control.kind==="panel"&&t.control.panel==="color").id;const group=layerApp.app.layout(innerWidth,innerHeight).groups.find(g=>g.panels.includes("navigator"));layerApp.dispatch({type:"move_panel",panel:"toolbar",target:{kind:"tab",group:group.id,index:null}});send({type:"set_column_collapsed",group:group.id,collapsed:true});})()');
  await settle();
  await click('.collapsed-column [data-panel="toolbar"]');
  await wait('[...document.querySelectorAll(".content-drawer [data-tile] button")].some(n=>Number(n.parentElement.dataset.tile)===editorDrawerTile)');
  await evaluate('new Promise(r=>setTimeout(r,200))');
  assert.ok(await evaluate('!!document.querySelector(".content-drawer .tile-divider")'),"Toolbar divider is a separator");
  await evaluate('[...document.querySelectorAll(".content-drawer [data-tile] button")].find(n=>Number(n.parentElement.dataset.tile)===editorDrawerTile).click()');
  await settle();
  await wait('!!document.querySelector(".content-drawer[data-drawer=tool] .color-wheel")');
  await evaluate('new Promise(r=>setTimeout(r,200))');
  assert.ok(await evaluate('document.querySelector(".content-drawer[data-drawer=tool]").getBoundingClientRect().width>=280'),"Nested content drawer uses measured toolbar anchor");
  await pointer("#canvas",.5,.5);
  await wait('!document.querySelector(".content-drawer[data-drawer=tool]")');
  await evaluate('layerApp.dispatch({type:"restore_workspace",workspace:editorWorkspace})');
  await settle();
  console.log("Navigator, partial Zen, collapsed columns, nested drawers, dividers passed");
  // Real Wasm save/open/export with an in-memory implementation only of the
  // browser's file transport. Check bytes and shared checkpoints, not mock models.
  await evaluate(`window.editorFiles=new Map();window.editorSavedPickers=[window.showSaveFilePicker,window.showOpenFilePicker];
    window.showSaveFilePicker=async options=>({name:options.suggestedName,async createWritable(){let bytes;return{async write(value){bytes=new Uint8Array(value)},async close(){editorFiles.set(options.suggestedName,bytes)},async abort(){}}}});
    window.showOpenFilePicker=async()=>[{name:"roundtrip.capy",async getFile(){return new File([editorFiles.get([...editorFiles.keys()].find(k=>k.endsWith(".capy")))],"roundtrip.capy")}}];`);
  await invoke("fit_canvas");
  await pointer("#canvas",.50,.50,[65,20]);
  assert.ok(await evaluate('layerApp.state().document_file.modified'));
  await evaluate('(()=>{const effect=layerApp.state().adjustments.find(a=>a.id.includes("domain_warp"));if(!effect)throw Error("Domain Warp missing");layerApp.dispatch(effect.action);})()');
  await settle();
  await invoke("save_document_as");
  await wait('!layerApp.state().document_file.busy');
  assert.equal(await evaluate('layerApp.state().document_file.modified'),false);
  assert.ok(await evaluate('[...editorFiles.entries()].some(([name,bytes])=>name.endsWith(".capy")&&bytes.length>100)'));
  await invoke("export_document");
  await wait('!layerApp.state().document_file.busy');
  assert.deepEqual(await evaluate('[...editorFiles.entries()].find(([name])=>name.endsWith(".png"))?.[1].slice(0,8)&&Array.from([...editorFiles.entries()].find(([name])=>name.endsWith(".png"))[1].slice(0,8))'),[137,80,78,71,13,10,26,10]);
  await invoke("new_document");
  await wait('!!document.querySelector(".document-dialog input[type=number]")');
  await evaluate('document.querySelectorAll(".document-dialog input").forEach((n,i)=>n.value=i?240:320); [...document.querySelectorAll(".document-dialog button")].find(n=>n.textContent==="Create").click()');
  await wait('layerApp.state().tabs[0].width===320 && !layerApp.state().document_file.busy');
  await evaluate('window.editorPrepare=layerApp.app.prepare_document.bind(layerApp.app);layerApp.app.prepare_document=(...args)=>{const result=editorPrepare(...args);layerApp.dispatch({type:"invoke",command:"pen"});return result;}');
  await invoke("open_document");
  await wait('layerApp.state().document_file.location?.name==="roundtrip.capy" && !layerApp.state().document_file.busy');
  await evaluate('delete layerApp.app.prepare_document');
  await wait('layerApp.app.brush_ready()');
  assert.equal(await evaluate('layerApp.state().brush.tool'),"pen","A brush selected while opening is retained");
  assert.ok(await evaluate('layerApp.state().tabs[0].width>320'));
  await evaluate('layerApp.dispatch({type:"select_layer",id:layerApp.state().layers.find(l=>l.label==="Current ink").id})');
  await settle();
  await pointer("#canvas",.5,.5,[30,0]);
  assert.ok(await evaluate("layerApp.state().document_file.modified"),"Painting the loaded project marks it modified");
  await invoke("new_document");
  await wait('!![...document.querySelectorAll(".document-dialog h2")].find(n=>n.textContent.includes("Save changes"))');
  await click(".document-dialog footer button");
  assert.equal(await evaluate('layerApp.state().document_file.modified'),true,"Cancel preserves unsaved drawing");
  await evaluate('window.editorSavePicker=showSaveFilePicker;window.showSaveFilePicker=async()=>{throw new DOMException("Cancelled","AbortError")}');
  await invoke("save_document_as");
  await wait('!layerApp.state().document_file.busy');
  assert.equal(await evaluate('layerApp.state().document_file.modified'),true,"Cancelled file picker does not mark edits saved");
  await evaluate('window.showSaveFilePicker=editorSavePicker');
  await invoke("close_document");
  await wait('!!document.querySelector(".document-dialog")');
  await evaluate('[...document.querySelectorAll(".document-dialog button")].find(n=>n.textContent==="Discard Changes").click()');
  await wait('!layerApp.state().document_file.close_ready && layerApp.state().document_file.location==null && !layerApp.state().document_file.modified');
  await evaluate('layerApp.dispatch({type:"restore_workspace",workspace:editorWorkspace}); layerApp.dispatch({type:"restore_settings",settings:editorSettings}); [window.showSaveFilePicker,window.showOpenFilePicker]=editorSavedPickers;');
  await settle();
  await evaluate('window.dispatchEvent(new Event("pagehide"))');
  assert.ok(await evaluate('!!JSON.parse(localStorage.getItem("layer.workspace.v1")).layout.panels.find(p=>p.id==="commands")'));
  const directory=process.env.LAYER_TEST_ARTIFACTS||"artifacts/web";
  await mkdir(directory,{recursive:true});
  const image=await call("Page.captureScreenshot",{format:"png"});
  await writeFile(`${directory}/editor-parity.png`,Buffer.from(image.data,"base64"));
  console.log("Project save/open/new, PNG export, unsaved cancellation, persistence passed");
}
