import assert from "node:assert/strict";

// Actual browser adoption boundary: a rejected HDR file must leave the current
// SDR drawing and its undo history usable. Fixtures are generated by the GTK
// journey and tools/validation/hdr_reference.py, not browser-side mock decoders.
// Stage the generated PQ input at pkg/hdr-pq.png and a saved HDR native master
// at pkg/hdr-master.capy before running test.mjs --hdr-limits.
export async function checkHdrLimits({evaluate}) {
  const wait = condition => evaluate(`new Promise((resolve,reject)=>{
    const start=performance.now();function poll(){if(${condition})resolve(true);
    else if(performance.now()-start>60000)reject(Error(document.body.innerText.slice(-1600)));
    else setTimeout(poll,30)}poll()})`);
  await wait("layerApp.startupTimes.complete!==null && layerApp.app.brush_ready()");
  const before = await evaluate("JSON.stringify(layerApp.app.document_color())");
  const epoch = await evaluate("Number(layerApp.state().document_file.epoch)");
  for (const name of ["hdr-pq.png", "hdr-master.capy"]) {
    await evaluate(`window.showOpenFilePicker=async()=>[{name:${JSON.stringify(name)},
      async getFile(){return new File([await(await fetch('/pkg/'+${JSON.stringify(name)})).arrayBuffer()],${JSON.stringify(name)})}}]`);
    await evaluate("layerApp.dispatch({type:'invoke',command:'open_document'})");
    await wait("!layerApp.state().document_file.busy && layerApp.state().host_error?.includes('HDR editing is not enabled on Web')");
    assert.equal(await evaluate("JSON.stringify(layerApp.app.document_color())"), before);
    assert.equal(await evaluate("Number(layerApp.state().document_file.epoch)"), epoch);
    assert.ok(await evaluate("layerApp.app.brush_ready()"));
  }
  console.log("Browser rejects PQ photos and HDR masters before adoption; the SDR drawing stays usable");
}
